apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mnvise5kb-python 
  janus-idp.io/tekton: mnvise5kb-python
  backstage.io/kubernetes-id: mnvise5kb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mnvise5kb-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  